### ISSUE TITLE
Create Benchmarking Framework

### ISSUE THREAD

**Issue by jdpsen** [primeqa/primeqa#103]
_aferritto created the following on Apr 20:_  

 This will probably be an epic.

- [ ] Set config(s) to test
- [ ] Orchestrate running cofigs (parallelize)
- [ ] Gather results
- [ ] Combine with previous results to show improvement/degredation 

_Original issue: https://github.ibm.com/ai-foundation/PrimeQA/issues/141_

**Comment by jdpsen** [comment]
_On Apr 26, aferritto commented:_
Idea: Use MLFlow

- Artifact store: COS S3
- Backend Store: IBM Cloud Postgresql
- MLFLow server: run in IBM cloud or on IRIS VM

Links:
- https://towardsdatascience.com/deploy-mlflow-with-docker-compose-8059f16b6039
- https://mlflow.org/docs/latest/quickstart.html
- https://mlflow.org/docs/latest/tracking.html#tracking-server
- https://mlflow.org/docs/latest/tracking.html

**Comment by jdpsen** [comment]
@bhavani105 : have we really worked on this/ are we planning to ? please update the pipeline accordingly.

**Comment by bhavani105** [comment]
Currently not in plan.
