### ISSUE TITLE
Extend QG for tables to Table+Text

### ISSUE THREAD

**Issue by jdpsen** [primeqa/primeqa#133]
_jaydesen created the following on Feb 01:_  

 How to design a QG mechanism for Table+text setup i.e. generate questions which needs information from both modalities.  

_Original issue: https://github.ibm.com/ai-foundation/PrimeQA/issues/18_

**Comment by jdpsen** [comment]
_On Feb 08, jaydesen commented:_
One possible baseline is to reduce the QG over table+text to QG over table by augmenting a given table with additional information coming from related text passages. A related paper is : https://aclanthology.org/2021.naacl-main.469.pdf

We are brainstorming over two main questions:
(1) Retrieval Aware QG: How to generate a question that has sufficient information to retrieve "unique" documents 
(2) Has multi-hope QG been explored over text data e.g. QG for HotpotQA ?

**Comment by jdpsen** [comment]
_On Feb 08, saneem-cg commented:_
Table+Text question generation looks for a multi-hop question generation pipeline where hops can be both in tables and passages. Initial step is to look for existing methods in multi-hop reading comprehension question generation domain and find methods/tricks which can be borrowed to table+textQA setup. 

This comment might be updated with more paper details.

**Multi-hop question generation**
- Gupta et. al. _Reinforced Multi-task Approach for Multi-hop Question Generation_, COLING 2020 [paper](https://aclanthology.org/2020.coling-main.249.pdf)
- Pan et. al. _Semantic Graphs for Generating Deep Questions_, ACL 2020 [paper](https://aclanthology.org/2020.acl-main.135.pdf)
- Yu et. al. _Low-Resource Generation of Multi-hop Reasoning Questions_, ACL 2020 [paper](https://aclanthology.org/2020.acl-main.601.pdf)
- Su et. al. _Multi-hop Question Generation with Graph Convolutional Network_, EMNLP Findings 2020 [paper](https://aclanthology.org/2020.findings-emnlp.416.pdf)
- Huang et. al. _Latent Reasoning for Low-Resource Question Generation_, ACL Findings 2021 [paper](https://aclanthology.org/2021.findings-acl.265.pdf)

**Table+Text Question Generation**
- Pan et. al. _Unsupervised Multi-hop Question Answering by Question Generation_, NAACL 2021 [paper](https://aclanthology.org/2021.naacl-main.469.pdf)

This [github page](https://github.com/teacherpeterpan/Question-Generation-Paper-List) is a good source to find published question generation papers.

**Comment by jdpsen** [comment]
_On Mar 15, jaydesen commented:_
@saneem-cg : put your updates here

**Comment by jdpsen** [comment]
Hey @riyazbhat I’m using Zenhub in GitHub, [click this link](https://app.zenhub.com/workspaces/primeqa-62acaf2dfbf2b600129ae0b7/board) to join my workspace and see other features available in GitHub or [download the Zenhub extension](https://www.zenhub.com/extension) and sign up with your GitHub account. 
  _Posted using [Zenhub](https://www.zenhub.com)_

**Comment by riyazbhat** [comment]
* Extended the QG over Hybrid context by adding
   - Path sampler for inference
   - Processor for training
