### ISSUE TITLE
Implement paragraph tag tokens in RC pipeline

### ISSUE THREAD

**Issue by jdpsen** [primeqa/primeqa#136]
_aferritto created the following on Feb 22:_  

  

_Original issue: https://github.ibm.com/ai-foundation/PrimeQA/issues/44_

**Comment by jdpsen** [comment]
@bhavani105 : please update the status and the pipeline label for this issue

**Comment by bhavani105** [comment]
This is not needed as NQ implementation achieves good performance without it as per the PR https://github.com/primeqa/primeqa/pull/255
