### ISSUE TITLE
Improve CI pipeline reliability

### ISSUE THREAD

**Issue by jdpsen** [primeqa/primeqa#142]
_aferritto created the following on Mar 31:_  

 The unit tests need to download models from HF's S3 server.  Models are then cached locally but present a challenge for CI tests.  Both caching (which creates many GB of Travis caches) and marking fixtures as flaky have been attempted, however this resource dependency makes the CI pipeline unstable.

When downloading resources from S3 there are intermittent errors/rate limiting which will sometimes kill the CI job.  This requires the job to be re-run manually.

This will usually show up as e.g. 3.7 and 3.9 passing but 3.8 failing (which then needs to be re-run manually).  In addition to manually re-running the time to re-download from S3 each test is not desirable. 

_Original issue: https://github.ibm.com/ai-foundation/PrimeQA/issues/82_

**Comment by jdpsen** [comment]
_On Apr 07, aferritto commented:_
I've removed the caching for now as it was not solving the issue.  We may need to ask HF for suggestions here as this will make it harder to merge PRs.

**Comment by jdpsen** [comment]
_On Apr 25, aferritto commented:_
@zhangr any updates on this issue?

**Comment by jdpsen** [comment]
@rongzhangibm : please update the status and the pipeline label for this issue

**Comment by rongzhangibm** [comment]
The issue was raised for Travis CI test. Since we now use Github Action, this issue can be closed.

**Comment by bhavani105** [comment]
Closing as we have moved to Github Actions
