### ISSUE TITLE
One-QA V1 release: BooleanQA: unified classifier

### ISSUE THREAD

**Issue by jdpsen** [primeqa/primeqa#143]
_jsmc created the following on Apr 12:_  

 We have a unified classifier that handles both the question type classification and the evidence classification, based on run_glue.py.  Per Sara, the was reproducing old results in train/decode mode, but there is are bugs in decode-only mode.
Seems to be an issue with underlying DataSet class having unexpected behavior. 

_Original issue: https://github.ibm.com/ai-foundation/PrimeQA/issues/102_

**Comment by jdpsen** [comment]
_On May 19, jsmc commented:_
we have a decode-only version of the classifier that runs in the one-qa code base with existing pretrained models, and produces results consistent with the leaderboard submission.

**Comment by jsmcibm** [comment]
inference-only pipeline for boolean questions in Tydi incorporated into run_mrc.py - unified classifier is called by run_mrc.py
