### ISSUE TITLE
One-QA V1 release: BooleanQA: master script

### ISSUE THREAD

**Issue by jdpsen** [primeqa/primeqa#147]
_jsmc created the following on Apr 12:_  

 Single script for decode-only Tydi-boolean system. 
Takes as input the output of the MRC system (factoid only questions), and the Tydi DataSet.
Outputs: complete Tydi output factoid+boolean questions.

depends upon #102 #103 #104 #105 
 

_Original issue: https://github.ibm.com/ai-foundation/PrimeQA/issues/106_

**Comment by jdpsen** [comment]
_On May 19, jsmc commented:_
Looks like the master script will be run_mrc.py itself.  Proposed structure

```
option: --do_tydi_boolean_questions_eval
forces --postprocessor oneqa.boolqa.processors.postprocessors.extractive.ExtractivePipelinePostProcessor
# adds question, language to eval_predictions.json
# we are only promising eval, not yet --do_tydi_boolean_questions_train

at end of main()

# we already have eval_predictions*.json at this point, and metrics have been done
if args.do_tydi_boolean_questions_eval:
  release_extractive_model_from_gpu()
  nway_classifier.main( task="boolean_vs_factoid_questions", ... qtc_args)
  nway_classifier.main( task="yes_vs_no", ... evc_args)
  score_normalize()
  # there is now an additional version of eval_predictions_processed.json
  do_TydiF1_again()  
  ```

nway_classifier.py is standalone component
it supports reading its dataset from eval_predictions.json
it outputs another eval_predictions.json, with additional fields
it has its own preprocessor and post-processor
it is not compatible with OneQA MRCTrainer class because it uses
HF-style RobertForSequenceClassification rather than OneQA style RobertaModelForDownstreamTasks
it has additional arguments (input location, model location, are we doing qtc or evc)

**Comment by jsmcibm** [comment]
inference-only pipeline for boolean questions in Tydi incorporated into run_mrc.py - master script not needed
