### ISSUE TITLE
Baleen demo

### ISSUE THREAD

**Issue by jdpsen** [primeqa/primeqa#156]
_bsiyer created the following on May 06:_  

 This is the epic for the Baleen demo.
As part of this, we will be creating template for future OneQA demos to follow. 

_Original issue: https://github.ibm.com/ai-foundation/PrimeQA/issues/181_

**Comment by jdpsen** [comment]
@bhavani105 : is this in PrimeQA radar ? Any update ? please update the status and the pipeline label for this issue

**Comment by bhavani105** [comment]
This is not targetted for PrimeQA
