### ISSUE TITLE
DPR-based IR engine 

### ISSUE THREAD

**Issue by jdpsen** [primeqa/primeqa#169]
_mrglass created the following on Jun 08:_  

  

_Original issue: https://github.ibm.com/ai-foundation/PrimeQA/pull/227_

**Comment by jdpsen** [comment]
Not in PrimeQA scope as of now.

**Comment by franzmpub** [comment]
First cut of support for training on DPR-style data.

**Comment by jdpsen** [comment]
Training is functional. 
Indexing - InProgress
Search - ToDo

**Comment by jdpsen** [comment]
Search - v1 in test. 
unexpected results: oob DPR > NQ finetuned DPR on monolingual xor tydi.
investigations about DPR training/search.

enabling checkpoints in DPR training - wip.

**Comment by franzmpub** [comment]
Added fixes to deal with data based on quoted TSV  in `dataloader_biencoder.py`, and for `max_doc_length` in `index_simple_corpus.py`.

Pushed the code to support search.

The full pipeline (training/indexing/search) looks fine, based on results using the English version of the XOR TyDi task.

**Comment by jdpsen** [comment]
DPR Basic functionality done. 
ToDos: PrimeQA extras : tests/notebooks etc.

**Comment by jdpsen** [comment]
Training/Indexing/search with checkpoints all done - in PR
implementation functionality testing: tested on monolingual tydi. training improves performance, rough ballpark number matches.
started with documentation and PrimeQA extras

**Comment by jdpsen** [comment]
DPR- NQ result reproduction- wip.

**Comment by franzmpub** [comment]
**XOR-TyDi, English(GMT)**
| R@5kt | R@2kt | model |
|-------|-------|-------|
| 69.6 | 62.2 | baseline, from https://arxiv.org/pdf/2010.11856.pdf, table 13 |
| 70.2 | 64.3 | PrimeQA, 30 negatives per query and positive (plus in-batch), 728k instances, 3 epochs |

**Comment by jdpsen** [comment]
DPR searcher with multiple queries.

**Comment by franzmpub** [comment]
Additional comparison on XOR-TyDi, including DPR on cross-lingual (XL) version of XOR-TyDi.
All results are on the XOR-TyDi Retrieve task (no answer selection), XOR-TyDi dev set (2113 queries).

| R@5kt | R@2kt | model |
|-------|-------|-------|
| 75.1 | 70.1 | ColBERT, En, trained on En (NQ -> En XOR) |
| 44.9 | 35.0 | ColBERT, XL, trained on En (NQ), *vanilla V2 |
| 73.3 | 67.4 | ColBERT, XL, after S/T training |
| 69.6 | 62.2 | DPR, En, XOR-TyDi paper (https://arxiv.org/pdf/2010.11856.pdf, table 13) |
| 70.2 | 64.3 | DPR, En, trained on En (human) version of XOR |
| **36.3** | **29.3** | DPR, XL, trained on original version of XOR |

**Comment by franzmpub** [comment]
Timing and size comparison against ColBERT (PLAID)
| index disk size [MB] | max RAM [MB] | time [s/query] | model |
|-------|-------|-------|-------|
| 244 | 268 | 0.26 | ColBERT (PLAID) |
| 123 | 84 | 0.47 | PrimeQA DPR |

**Comment by jdpsen** [comment]
bert-base-multilingual is too slow, should recheck with another machine.

**Comment by franzmpub** [comment]
DPR, using 1 A100, running the XOR-TyDi dev test, all results are averages of 10 runs.
| queries/s | run |
|-------|-------|
| 10.6 | faiss 1.7.0 from conda, bsize 1 |
| 14.4 | faiss 1.7.0 from conda, bsize 16 |
| 4.90 | faiss 1.7.2 from pip, bsize 1 |
| 5.98 | faiss 1.7.2 from pip, bsize 16 |
