### ISSUE TITLE
Add Doc Coverage

### ISSUE THREAD

**Issue by jdpsen** [primeqa/primeqa#179]
_aferritto created the following on Apr 18:_  

 https://www.sphinx-doc.org/en/master/usage/extensions/coverage.html 

_Original issue: https://github.ibm.com/ai-foundation/PrimeQA/issues/129_

**Comment by jdpsen** [comment]
@bhavani105 : Have we done this ? Please update the status/pipeline of this issue correctly.

**Comment by bhavani105** [comment]
Closing this as documentation work is covered under https://github.com/primeqa/primeqa/pull/294
