### ISSUE TITLE
Refine Documentation

### ISSUE THREAD

**Issue by jdpsen** [primeqa/primeqa#209]
_aferritto created the following on Apr 15:_  

 Follow up from #98

#98 establishes a basic sphinx build setup which recursively documents the oneqa API.
We should refine the `.rst` files to extend this basic API documentation and provide a better user experience.

We will likely want to wait until there is more code (with documentation too) in master before working on this.
Since this will likely not be done until after issues that have not been created yet are completed, I am applying the `blocked` label. 

_Original issue: https://github.ibm.com/ai-foundation/PrimeQA/issues/125_

**Comment by jdpsen** [comment]
@bhavani105 : is it complete or being actively worked on ? Please update the status/pipeline accordingly.

**Comment by bhavani105** [comment]
Closing this as its covered under https://github.com/primeqa/primeqa/issues/279
