### ISSUE TITLE
Decide on Coding style

### ISSUE THREAD

**Issue by jdpsen** [primeqa/primeqa#210]
_aferritto created the following on Apr 18:_  

 I think https://pypi.org/project/black/ is the standard for python and will auto-format our code.  May want to look at flake8 too: https://pypi.org/project/flake8/.

Some links:
- http://www.sefidian.com/2021/08/03/how-to-use-black-flake8-and-isort-to-format-python-codes/
- https://ljvmiranda921.github.io/notebook/2018/06/21/precommits-using-black-and-flake8/ 

_Original issue: https://github.ibm.com/ai-foundation/PrimeQA/issues/126_

**Comment by jdpsen** [comment]
_On Apr 18, aferritto commented:_
Created an issue @jaydesen

**Comment by jdpsen** [comment]
This is now documented. We can review it later on demand.

**Comment by kpfadnis** [comment]
@jdpsen @avisil @bhavani105 Maybe we should add `Development Practices`/`Coding Style` section in `development` README and ask developers to run `black` formatter for newer python files. 

In long run, I would recommend setting `pre-commit` hooks with `black` so that coding style of repo converges.
