### ISSUE TITLE
Document LMs Supported for MRC

### ISSUE THREAD

**Issue by jdpsen** [primeqa/primeqa#218]
_aferritto created the following on Apr 29:_  

 See MRC tests parameterization for list of model names which are validated.  Note this includes english only models whereas tydi is multilingual. 

_Original issue: https://github.ibm.com/ai-foundation/PrimeQA/issues/168_

**Comment by jdpsen** [comment]
I think this is done. @bhavani105 please confirm if we can close this.

**Comment by bhavani105** [comment]
MRC tests currently only test the english models. There is no test for xlm-roberta.  Given the constraints of Github Actions resources, it would be difficult to add  expand the list of models.
