### ISSUE TITLE
MRC Set Features from PreProcessor

### ISSUE THREAD

**Issue by jdpsen** [primeqa/primeqa#219]
_aferritto created the following on Apr 29:_  

 Idea: When loading data from disk file (e.g. json), set the `features` field of `datasets.load_dataset` based on a new method of preprocessors where the preprocessor gathers the feature types class attrs.

This would help with schema mismatches where int64 is inferred but int32 is needed.

Alternatively could set the features == check to be a new method which recursively checks the tree structure for equality but considers e.g. int32 == int64. 

_Original issue: https://github.ibm.com/ai-foundation/PrimeQA/issues/169_

**Comment by jdpsen** [comment]
@bhavani105 : could you please update this issue with the current status and categorize it accordingly done/inProress/backlog/icebox.

**Comment by bhavani105** [comment]
Currently this feature has not be required for the dataset currently supported
