### ISSUE TITLE
Add Support for Loading Data In BasePreProcessor Format

### ISSUE THREAD

**Issue by jdpsen** [primeqa/primeqa#227]
_aferritto created the following on Apr 27:_  

 take guidance from HF run_qa.py 

_Original issue: https://github.ibm.com/ai-foundation/PrimeQA/issues/163_

**Comment by jdpsen** [comment]
_On Apr 29, aferritto commented:_
I've started looking into making this work. 

Branch: https://github.ibm.com/ai-foundation/OneQA/tree/user-data-base-format

I have the tests passing, however there are some rough edges when trying to get the main pipeline running.  Currently the preprocessor says for eval data the `target` is optional.  However the postprocessor treats it as required.  I am thinking the best approach is to make it required for eval in the preprocessor schema.  This should make it work.

Then longer term we can support `--do_test` which will require some extra code (particularly in trainer) to support.

There is another challenge.  HF datasets does not want to load dataset where train and test have different schemas.  This will require some solution to allow supporting do_test with no gold labels.

**Comment by jdpsen** [comment]
_On May 03, aferritto commented:_
Model seems to be training and decoding well.  Next hurdle is metrics.  The TyDi F1 is not well suited to this.  I think the NQ F1 is the right move here and will be one less thing needed for #43.

**Comment by jdpsen** [comment]
@bhavani105 : could you please update this issue with the current status and categorize it accordingly done/inProress/backlog/icebox.

**Comment by bhavani105** [comment]
Do we want to add a  `--do_predict `option to run_mrc.py ?
Do we want to support different schemas of the train and eval datasets ?

**Comment by bhavani105** [comment]
We want to support mixing data from different datasets e.g. NQ and TyDI but evaluate only on one.
We should support --do_predict
