### ISSUE TITLE
train_mrc.py fails

### ISSUE THREAD

**Issue by hansolosan** [primeqa/primeqa#254]
I'm trying to train a model using the command in the README.me, but it fails while accessing a value in the dataset:

:~/sandbox2/primeqa$ python examples/mrc/run_mrc.py --model_name_or_path xlm-roberta-large        --output_dir models/trained-tydi --fp16 --learning_rate 4e-5        --do_train --do_eval --per_device_train_batch_size 16        --per_device_eval_batch_size 128 --gradient_accumulation_steps 4        --warmup_ratio 0.1 --weight_decay 0.1 --save_steps 50000        --
overwrite_output_dir --num_train_epochs 1 --evaluation_strategy no
Some weights of XLMRobertaModelForDownstreamTasks were not initialized from the model checkpoint at xlm-roberta-large and are newly initialized: ['task_heads.qa_head.qa_outputs.bias', 'task_heads.qa_head.classifier.dense.bias', 'task_heads.qa_head.classifier.out_proj.bias', 'task_heads.qa_head.qa_outputs.weight', 'task_heads.qa_head.classifier.dense.weight', 'task_heads.qa_head.classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Reusing dataset tydiqa (/home/raduf/.cache/huggingface/datasets/tydiqa/primary_task/1.0.0/b8a6c4c0db10bf5703d7b36645e5dbae821b8c0e902dac9daeecd459a8337148)
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 829.82it/s]
Parameter 'function'=<function TyDiQAPreprocessor._rename_examples at 0x7fd0f79b29d0> of the transform datasets.arrow_dataset.Dataset._map_single couldn't be hashed properly, a random hash was used instead. Make sure your transforms and parameters are serializable with pickle or dill for the dataset fingerprinting and caching to work. If you reuse this transform, the caching mechanism will consider it to be different from the previous calls and recompute everything. This warning is only showed once. Subsequent hashing failures won't be showed.
Loading cached processed dataset at /home/raduf/.cache/huggingface/datasets/tydiqa/primary_task/1.0.0/b8a6c4c0db10bf5703d7b36645e5dbae821b8c0e902dac9daeecd459a8337148/cache-1c80317fa3b1799d.arrow
Loading cached processed dataset at /home/raduf/.cache/huggingface/datasets/tydiqa/primary_task/1.0.0/b8a6c4c0db10bf5703d7b36645e5dbae821b8c0e902dac9daeecd459a8337148/cache-bdd640fb06671ad1.arrow
Loading cached processed dataset at /home/raduf/.cache/huggingface/datasets/tydiqa/primary_task/1.0.0/b8a6c4c0db10bf5703d7b36645e5dbae821b8c0e902dac9daeecd459a8337148/cache-3eb13b9046685257.arrow
Loading cached processed dataset at /home/raduf/.cache/huggingface/datasets/tydiqa/primary_task/1.0.0/b8a6c4c0db10bf5703d7b36645e5dbae821b8c0e902dac9daeecd459a8337148/cache-23b8c1e9392456de.arrow
Traceback (most recent call last):
  File "/home/raduf/sandbox2/primeqa/examples/mrc/run_mrc.py", line 501, in <module>
    main()
  File "/home/raduf/sandbox2/primeqa/examples/mrc/run_mrc.py", line 385, in main
    _, train_dataset = preprocessor.process_train(train_dataset)
  File "/home/raduf/sandbox2/primeqa/primeqa/mrc/processors/preprocessors/base.py", line 75, in process_train
    return self._process(examples, is_train=True)
  File "/home/raduf/sandbox2/primeqa/primeqa/mrc/processors/preprocessors/base.py", line 99, in _process
    features = self.subsample_features(features)
  File "/home/raduf/sandbox2/primeqa/primeqa/mrc/processors/preprocessors/base.py", line 303, in subsample_features
    keep_indices = [i for i, st in enumerate(dataset['subsample_type']) if self._keep_feature(st)]
  File "/home/raduf/anaconda3/envs/primeqa/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 1765, in __getitem__
    return self._getitem(
  File "/home/raduf/anaconda3/envs/primeqa/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 1749, in _getitem
    pa_subtable = query_table(self._data, key, indices=self._indices if self._indices is not None else None)
  File "/home/raduf/anaconda3/envs/primeqa/lib/python3.9/site-packages/datasets/formatting/formatting.py", line 483, in query_table
    _check_valid_column_key(key, table.column_names)
  File "/home/raduf/anaconda3/envs/primeqa/lib/python3.9/site-packages/datasets/formatting/formatting.py", line 423, in _check_valid_column_key
    raise KeyError(f"Column {key} not in the dataset. Current columns in the dataset: {columns}")
KeyError: "Column subsample_type not in the dataset. Current columns in the dataset: ['example_id', 'input_ids', 'attention_mask', 'offset_mapping', 'example_idx']"

Any help would be appreciated.

**Comment by bhavani105** [comment]
Hi Hans
This happens if there is a stale dataset cache.

Please try deleting  /home/raduf/.cache/huggingface/datasets/tydiqa/
and rerunning

Bhavani

**Comment by mihaela-bornea** [comment]
Hello. I am not sure if you got help for this. Can you please add --overwrite_cache  option to the command line if you still have the problem..

From: Hans Florian ***@***.***>
Date: Friday, July 1, 2022 at 3:01 PM
To: primeqa/primeqa ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] [primeqa/primeqa] train_mrc.py fails (Issue #254)
I'm trying to train a model using the command in the README.me, but it fails while accessing a value in the dataset: :~/sandbox2/primeqa$ python examples/mrc/run_mrc.py --model_name_or_path xlm-roberta-large --output_dir models/trained-tydi
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
ZjQcmQRYFpfptBannerEnd

I'm trying to train a model using the command in the README.me, but it fails while accessing a value in the dataset:

:~/sandbox2/primeqa$ python examples/mrc/run_mrc.py --model_name_or_path xlm-roberta-large --output_dir models/trained-tydi --fp16 --learning_rate 4e-5 --do_train --do_eval --per_device_train_batch_size 16 --per_device_eval_batch_size 128 --gradient_accumulation_steps 4 --warmup_ratio 0.1 --weight_decay 0.1 --save_steps 50000 --
overwrite_output_dir --num_train_epochs 1 --evaluation_strategy no
Some weights of XLMRobertaModelForDownstreamTasks were not initialized from the model checkpoint at xlm-roberta-large and are newly initialized: ['task_heads.qa_head.qa_outputs.bias', 'task_heads.qa_head.classifier.dense.bias', 'task_heads.qa_head.classifier.out_proj.bias', 'task_heads.qa_head.qa_outputs.weight', 'task_heads.qa_head.classifier.dense.weight', 'task_heads.qa_head.classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Reusing dataset tydiqa (/home/raduf/.cache/huggingface/datasets/tydiqa/primary_task/1.0.0/b8a6c4c0db10bf5703d7b36645e5dbae821b8c0e902dac9daeecd459a8337148)
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 829.82it/s]
Parameter 'function'=<function TyDiQAPreprocessor._rename_examples at 0x7fd0f79b29d0> of the transform datasets.arrow_dataset.Dataset._map_single couldn't be hashed properly, a random hash was used instead. Make sure your transforms and parameters are serializable with pickle or dill for the dataset fingerprinting and caching to work. If you reuse this transform, the caching mechanism will consider it to be different from the previous calls and recompute everything. This warning is only showed once. Subsequent hashing failures won't be showed.
Loading cached processed dataset at /home/raduf/.cache/huggingface/datasets/tydiqa/primary_task/1.0.0/b8a6c4c0db10bf5703d7b36645e5dbae821b8c0e902dac9daeecd459a8337148/cache-1c80317fa3b1799d.arrow
Loading cached processed dataset at /home/raduf/.cache/huggingface/datasets/tydiqa/primary_task/1.0.0/b8a6c4c0db10bf5703d7b36645e5dbae821b8c0e902dac9daeecd459a8337148/cache-bdd640fb06671ad1.arrow
Loading cached processed dataset at /home/raduf/.cache/huggingface/datasets/tydiqa/primary_task/1.0.0/b8a6c4c0db10bf5703d7b36645e5dbae821b8c0e902dac9daeecd459a8337148/cache-3eb13b9046685257.arrow
Loading cached processed dataset at /home/raduf/.cache/huggingface/datasets/tydiqa/primary_task/1.0.0/b8a6c4c0db10bf5703d7b36645e5dbae821b8c0e902dac9daeecd459a8337148/cache-23b8c1e9392456de.arrow
Traceback (most recent call last):
File "/home/raduf/sandbox2/primeqa/examples/mrc/run_mrc.py", line 501, in
main()
File "/home/raduf/sandbox2/primeqa/examples/mrc/run_mrc.py", line 385, in main
_, train_dataset = preprocessor.process_train(train_dataset)
File "/home/raduf/sandbox2/primeqa/primeqa/mrc/processors/preprocessors/base.py", line 75, in process_train
return self._process(examples, is_train=True)
File "/home/raduf/sandbox2/primeqa/primeqa/mrc/processors/preprocessors/base.py", line 99, in _process
features = self.subsample_features(features)
File "/home/raduf/sandbox2/primeqa/primeqa/mrc/processors/preprocessors/base.py", line 303, in subsample_features
keep_indices = [i for i, st in enumerate(dataset['subsample_type']) if self._keep_feature(st)]
File "/home/raduf/anaconda3/envs/primeqa/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 1765, in getitem
return self._getitem(
File "/home/raduf/anaconda3/envs/primeqa/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 1749, in _getitem
pa_subtable = query_table(self._data, key, indices=self._indices if self._indices is not None else None)
File "/home/raduf/anaconda3/envs/primeqa/lib/python3.9/site-packages/datasets/formatting/formatting.py", line 483, in query_table
_check_valid_column_key(key, table.column_names)
File "/home/raduf/anaconda3/envs/primeqa/lib/python3.9/site-packages/datasets/formatting/formatting.py", line 423, in _check_valid_column_key
raise KeyError(f"Column {key} not in the dataset. Current columns in the dataset: {columns}")
KeyError: "Column subsample_type not in the dataset. Current columns in the dataset: ['example_id', 'input_ids', 'attention_mask', 'offset_mapping', 'example_idx']"

Any help would be appreciated.
