### ISSUE TITLE
Caching Issues - Running out of Disk Space

### ISSUE THREAD

**Issue by seirasto** [primeqa/primeqa#259]
There seems to be a couple of issues with caching the datasets:

1. The cache does not realize when the original dataset files have been updated. --overwrite_cache must be used in this case. Can we add a simple check for this as well?
2. Hash Error which causes tokenization to be rerun and multiple caches of same data: 
```
of the transform datasets.arrow_dataset.Dataset._map_single couldn't be hashed properly, a random hash was used instead. Make sure your transforms and parameters are serializable with pickle or dill for the dataset fingerprinting and caching to work. If you reuse this transform, the caching mechanism will consider it to be different from the previous calls and recompute everything. This warning is only showed once. Subsequent hashing failures won't be showed.
```
 This seems to be a known issue: https://github.com/huggingface/datasets/issues/4506#issuecomment-1157417219 It is happening in other versions as well not just 3.9. We may be able to resolve with an older version of dill: `pip install "dill<0.3.5"`

3.  Datasets with overlapping files will be stored as multiple caches. This causes me to run out of disk space quickly. For example, if I have an experiment that uses NQ and another that uses NQ + List Data they will be separate caches with significant overlap.

**Comment by bhavani105** [comment]
Related known issue:  https://github.com/huggingface/datasets/issues/3847

**Comment by bhavani105** [comment]
Here is source code for datasets.fingerprints https://huggingface.co/docs/datasets/v1.12.0/_modules/datasets/fingerprint.html
See update_fingerprint() and finger_transform() functions.    The later has. a randomized_function arg that defaults to False.

There is a  Hasher class that accepts python objects as inputs.   The generate_fingerprint() method uses that.   If generate_fingerprint() fails (not clear why) the generate_random_fingerprint() is called.

**Comment by bhavani105** [comment]
Here's the message that indicates the custom Hasher is not being used.  

`Parameter 'function'=<function TyDiQAPreprocessor._rename_examples at 0x14f8cabd01f0> of the transform datasets.arrow_dataset.Dataset._map_single couldn't be hashed properly, a random hash was used instead. Make sure your transforms and parameters are serializable with pickle or dill for the dataset fingerprinting and caching to work. If you reuse this transform, the caching mechanism will consider it to be different from the previous calls and recompute everything. This warning is only showed once. Subsequent hashing failures won't be showed.`
