### ISSUE TITLE
Make PrimeQA pip installable

### ISSUE THREAD

**Issue by avisil** [primeqa/primeqa#276]

**Comment by jdpsen** [comment]
@bhavani105 : any update on the wheel file you can put it here.

**Comment by jdpsen** [comment]
Waiting for reorg branch to merge.

**Comment by jdpsen** [comment]
.whl file created for the latest release. 
@hansolosan : to test the .whl file.
Next: GH Actions can automatically push new .whl for every new tag update.

**Comment by bhavani105** [comment]
Addressed by this PR https://github.com/primeqa/primeqa/pull/295
