### ISSUE TITLE
Increase test cases for run_* script

### ISSUE THREAD

**Issue by jdpsen** [primeqa/primeqa#282]
reorg_run_* branch fails travis build success metric of  > 60% code coverage, likely because run_* scripts increases the total codelines. We need to add more test cases or decrease the code coverage threshold .

**Comment by bhavani105** [comment]
run_* scripts  have a main and therefore would not be included in the code coverage calculations.

**Comment by bhavani105** [comment]
Modified to exclude run_*.py scripts from coverage computation 
In .coveragerc
omit =
        */grpc_generated*
        */run_*.py

**Comment by jdpsen** [comment]
Not needed anymore, handled via the above changes.
