### ISSUE TITLE
Update datasets to >= 2.3

### ISSUE THREAD

**Issue by mxschmdt** [primeqa/primeqa#290]
Would it be possible to update the datasets dependency to >= 2.3?
In that version a bug was fixed which prevents re-using cached dataset transforms: https://github.com/huggingface/datasets/commit/ffbb21e6b2914632075aee11098f4310b3de82a8

**Comment by bhavani105** [comment]
Thank you.  We will test and update.  
@seirasto This may address the caching issues https://github.com/primeqa/primeqa/issues/259

**Comment by mxschmdt** [comment]
Maybe directly update to >= 2.4 since this version also fixes a hashing bug with Python 3.9 still occurring in datasets 2.3.1: https://github.com/huggingface/datasets/commit/6f03d2256c1caa6a3c551cb21ac760db35775361
(This is the bug addressed: https://github.com/huggingface/datasets/issues/4506)

It's also quite severe if you set a global random seed which leads to cached transforms being reused wrongly as the same hash might refer to different processings.

**Comment by jdpsen** [comment]
PR merged.
