### ISSUE TITLE
Research feature request: use multi perspective matching instead of cosine similarity for matching

### ISSUE THREAD

**Issue by hansolosan** [primeqa/primeqa#297]
I would like to investigate the use of multi-perspective matching instead of cosine similarity, as outlined  in https://arxiv.org/pdf/1702.03814.pdf%E3%80%82Bilateral. It gave a nice improvement in performance there..

**Comment by franzmpub** [comment]
Yes, I'll look into it.

**Comment by jdpsen** [comment]
@franzmpub : Is there any status change for this issue ? If yes, could you please update
