### ISSUE TITLE
Entity conditioned question generation

### ISSUE THREAD

**Issue by bhavani105** [primeqa/primeqa#306]
Implement  entity conditioned synthetic question generation for dense IR training based on the work:
**Entity-Conditioned Question Generation for Robust Attention
Distribution in Neural Information Retrieval**
https://arxiv.org/pdf/2204.11373

Enable reproducing the retrieval performance results on the NQ dataset and zero-shot on WebQuestions.

![image.png](https://images.zenhubusercontent.com/60db232fd740c445e00360b4/e618dd69-bc75-4051-85aa-b320539c6f47)

**Comment by gangiswag** [comment]
Each data point for training the entity-conditioned question generator is of the following format:

```
      {  "source": " The fourth season of  *=- Chicago Fire @#&  , an American drama television series with executive producer Dick Wolf , and producers Derek Haas , Michael Brandt , and Matt Olmstead , was ordered on February 5 , 2015 , by NBC , and premiered on October 13 , 2015 and concluded on May 17 , 2016 . The season contained 23 episodes . ",
        "target": "The ... episodes . madeupword0000 23 madeupword0001 how many episodes are in chicago fire season 4\n",
        "conditioned_entity": "Chicago Fire" }
 ```

**Comment by gangiswag** [comment]
Script to train the model:

```python train.py \
    --do_train \
    --train_file <path to train data> \
    --learning_rate 3e-5 \
    --num_epochs 4 \
    --train_batch_size 32 \
    --max_length 512 \
    --max_answer_length 128 \
    --output_dir <path to output dir>
    ```
