### ISSUE TITLE
Support for MuMuQA a multi-hop QA task over image-caption pairs

### ISSUE THREAD

**Issue by bhavani105** [primeqa/primeqa#307]
Support for **MuMuQA** a benchmark QA task that involves multi-hop question answering over image-caption pairs.

Based on the paper MuMuQA: Multimedia Multi-Hop News Question Answering via
Cross-Media Knowledge Extraction and Grounding Reddy, R. G, et.al

https://ojs.aaai.org/index.php/AAAI/article/view/21370
https://gangiswag.github.io/data/AAAI_poster_MuMuQA.pdf
https://github.com/blender-nlp/MuMuQA

Be able to reproduce the baselines

**Comment by bhavani105** [comment]
Image feature extraction and representation is done using:

https://github.com/rbgirshick/py-faster-rcnn
https://github.com/microsoft/Oscar

**Comment by jdpsen** [comment]
@bhavani105  @gangiswag Is there any status update for this one ? If yes, could you please put it here ?
