### ISSUE TITLE
Support MRC model training with the combination of multiple datasets

### ISSUE THREAD

**Issue by rongzhangibm** [primeqa/primeqa#311]
For example, building a PrimeQA (multilingual) MRC model trained with both NQ and TyDI.

**Comment by rongzhangibm** [comment]
#### NQ ####

| Model | Short Answer F1 | Long Answer F1|
| - | - | - |
|IOTA| 56.80 | 68.40 |
|Conversion | 53.15| 64.94|
|Datasets Combination |54.51| 63.29|

#### Tydi ####

| Model | Short Answer F1 | Long Answer F1|
| - | - | - |
|IOTA| 68.80 | 73.0 |
|Conversion | 69.30| 74.20|
|Datasets Combination |67.70| 73.00|

**Comment by jdpsen** [comment]
Long answer F1 low ? Need some check here.

**Comment by rongzhangibm** [comment]
Experiments to improve PrimeQA MRC performance on NQ:

Easy:
1. Pre-train on SQuAD (keep in mind MLQA, XQuAD, too)
2. Hyper-parameter tuning (2D grid with lr (4 different values) and #epochs in {1, 2})

Medium:
1. Teacher 1: SQuAD -> NQ; Teacher 2: TyDI, Distill from both (hyper-parameter tuning)
2. 2/3 rounds of self-distillation
