### ISSUE TITLE
Integrate OmniTab in PrimeQA

### ISSUE THREAD

**Issue by jdpsen** [primeqa/primeqa#322]
OmniTab paper link: https://arxiv.org/pdf/2207.03637.pdf

**Comment by vishwajeetkumar93** [comment]
`OmniTab` experiments were based on `TAPEX` (Which is currently available on HF), the basic plan for integration of OmniTab to primeQA is as follows:

1. Bump up the Huggingface transformers version from 4.17.0 to latest (4.22.0).
2. Integrate Ta

**Comment by jdpsen** [comment]
We are integrating Tapex from HF, being tracked here #337
Working with Zhengbao with the following plan of action

- [ ] Zhengbao to upload models in HF which can used pretty much the same way how we use HF/Tapex 
- [ ] [IBM] Verify Zhengbao's modules from HF reproduce the results 
- [ ] Zhengabo to clean up his code to remove redundant TaBERT dependency. 
- [ ] [IBM] Take Zhengbao's code and integrate it in PrimeQA

**Comment by jdpsen** [comment]
Omnitab is being supported over Tapex. A PR from Zhengbao is in place, needs to be updated once Tapex is meged.
