### ISSUE TITLE
Fix terminologies

### ISSUE THREAD

**Issue by avisil** [primeqa/primeqa#328]
1. Change all IR/ Information Retrieval/ Info Retriever -> retriever including `run_ir.py` to `run_retriever.py` @franzmpub 
2. Change all MRC -> reader incl. `run_mrc.py` to `run_reader.py`. Also change in pipeline. @bhavani105 @seirasto 
3. TableQA -> Table Reader @vishwajeetkumar93 @jdpsen

**Comment by franzmpub** [comment]
Shall we start a common branch for this, rather than to have 3 (or more) separate branches and PRs?

**Comment by vishwajeetkumar93** [comment]
https://github.com/primeqa/primeqa/tree/fixing_terminologies Please use this branch to push your corresponding renaming changes.

**Comment by jdpsen** [comment]
TableQAModel is renamed to TapasReader, TapexReader now.
