### ISSUE TITLE
Run QG train and. inference from files on disk 

### ISSUE THREAD

**Issue by bhavani105** [primeqa/primeqa#354]
We need the capability and instructions to train and inference from data files on disk similar to the 
options in run_mrc.py
```
    train_file: Optional[str] = field(
        default=None, metadata={"help": "local file(s) to train on."}
    )
    eval_file: Optional[str] = field(
        default=None, metadata={"help": "local file(s) to test on."}
    )
```

Pls update qg/README.md instructions on how to do this.
This is required to run experiments and integration of QVE https://github.com/primeqa/primeqa/issues/305

**Comment by jdpsen** [comment]
@bhavani105 : please point me to a sample file I can use to test the functionality.
