### ISSUE TITLE
GPU Speed for evaluating with run_mrc.py 

### ISSUE THREAD

**Issue by seirasto** [primeqa/primeqa#377]
Eval run on TyDiQA dev set containing 18670 questions using `PrimeQA/nq_tydi_sq1-reader-xlmr_large-20221110`

Machine | Runtime (m) | M F1 | P F1 |
--- | --- | --- | --- |
10 CPU x 1 GPU | 36.83 | 69.21 | 73.36 |
10 CPU x 2 GPU | 25.06 | 69.21 | 73.36 |

Log files and output are available on CCC here: 

`/dccstor/srosent2/primeqa/experiments/2gpueval`
`/dccstor/srosent2/primeqa/experiments/1gpueval`

**Comment by jdpsen** [comment]
@seirasto @avisil : Do we have any follow up action items on this ?
