### ISSUE TITLE
Modify Reader component apply api to support multiple question-context pairs

### ISSUE THREAD

**Issue by bhavani105** [primeqa/primeqa#382]
Proposed API

`apply(self, questions: List[str], contexts: List[List[str]], example_ids: List[str] = None, *args, **kwargs)`

Returns a predictions as a dict where the key is the example id

**Comment by jdpsen** [comment]
@bhavani105 : could you please update the current status of this issue ?

**Comment by bhavani105** [comment]
Done and merged
