### ISSUE TITLE
Create readme for contributors as "Contributing to PrimeQA"

### ISSUE THREAD

**Issue by vishwajeetkumar93** [primeqa/primeqa#386]
We should have a readme with easy to follow steps with title "Contributing to PrimeQA".
We are very open to community contributions and appreciate anything that can improve primeqa.  To avoid unnecessary work on either side, please go through the following guidelines:

**Comment by vishwajeetkumar93** [comment]
- Move components from pipelines to one folder up to primeqa

- Code/algorithms sits in sub-packages

- Every new algorithm should have *_component.py extending base component and implementing all functions.

- Lynters and formatter for new code which we will add in future.

- Standardizing config file style and logger

**Comment by vishwajeetkumar93** [comment]
Move components from pipelines to one folder up to primeqa : https://github.com/primeqa/primeqa/blob/patch_components/primeqa/components/base.py

Every new algorithm should have *_component.py extending base component and implementing all functions. : https://github.com/primeqa/primeqa/blob/tapex_integration/primeqa/tableqa/tapex/tapex_component.py

**Comment by jdpsen** [comment]
> * Move components from pipelines to one folder up to primeqa
> 
>     * Code/algorithms sits in sub-packages
> 
>     * Every new algorithm should have *_component.py extending base component and implementing all functions.
> 
>     * Lynters and formatter for new code which we will add in future.
> 
>     * Standardizing config file style and logger 
-- also metrics

**Comment by vishwajeetkumar93** [comment]
Decisions:

- Move components from pipelines to one folder up to primeqa

- Code/algorithms sits in sub-packages

- Every new algorithm should have *_component.py extending base component and implementing all functions.

- Lynters and formatter for new code which we will add in future. [Kshithiz]

- Standardizing config file style and logger

- 

- MRC → reader and retriever

- TableQA → Table Reader [Not Done]

- TapexAccuracy → TapexReaderAccuracy [Not Done]

- V2 design → Extend Metrics from huggingface transformers. [Not Done]

- Standardizing folder structure.  [Check[]
