### ISSUE TITLE
DPR biencoder training `sample_negative_from_top_k` default value causes breaks

### ISSUE THREAD

**Issue by billll-ppp** [primeqa/primeqa#391]
Thanks for the great work! 
I encountered some errors when training a DPR retriever that seem to relate to this argument `sample_negative_from_top_k` causing the `randint` function to break;
![image](https://user-images.githubusercontent.com/60731287/205344073-f441d2cd-f807-439b-be4a-2a74cd00f96e.png)
After digging into it, I found that this commit (https://github.com/primeqa/primeqa/commit/115bf5c5bf06f5c62e07aec8361b19a9c8543e63), which I believe intended to change the logic on that value (eliminate the occurance of negative values in `sample_negative_from_top_k`) but left the default value unchanged. I think the new default value for this argument should be 1 now.
Hope you'll find my investigation helpful!

**Comment by jdpsen** [comment]
@franzmpub : Are you already looking into this issue ?
