### ISSUE TITLE
Service health check

### ISSUE THREAD

**Issue by assaftibm** [primeqa/primeqa#401]
Hi, 
I'm deploying primeqa on a Kubernetes cluster and I'm looking for a way to perform health-checks. 

In general, recent versions of Kubernetes have [built-in support](https://kubernetes.io/blog/2018/10/01/health-checking-grpc-servers-on-kubernetes/) for gRPC health check. However, for this to work, the application has to implement the standard [gRPC Health Checking Protocol](https://github.com/grpc/grpc/blob/master/doc/health-checking.md). Looking at primeqa code, I didn't find such implementation.

Is this something on the horizon? Or is there any other health-check mechanism that is already supported?

Thanks

**Comment by assaftibm** [comment]
Adding that for now I'm just using TCP health check on the gRPC port.

**Comment by kpfadnis** [comment]
@assaftibm It's a good suggestion. We will add a `health check` service in subsequent release.
