### ISSUE TITLE
ColBERT models to be packaged into ONE model file

### ISSUE THREAD

**Issue by avisil** [primeqa/primeqa#407]
Currently, checkpoint is downloaded and then if one chooses to index a corpus, then another copy of `xlm-roberta-base` models (config.json, pytorch_model.bin, sentencepiece.bpe.model, tokenizer.json) are downloaded from HF model hub. We need to package all into `model_name_or_path`.

**Comment by jdpsen** [comment]
@franzmpub : have we started on it ? Please put updates , if any
