### ISSUE TITLE
Test cases for primeqa/services

### ISSUE THREAD

**Issue by jdpsen** [primeqa/primeqa#427]
We need to have test cases covering code in primeqa/services. Current coverage  there are no test cases and hence pretty low coverage

**Comment by kpfadnis** [comment]
There is existing issue for `service` layer coverage. I need solid 2 week block without any changes to `service` layer to finish necessary re-structuring to add test coverage. 

Older issue  (#357) and PR (#359) which will get modified soon. 

Closing this as a duplicate of #357
