### ISSUE TITLE
Bug in MRC trainer evaluation "ValueError: The model did not return a loss from the inputs"

### ISSUE THREAD

**Issue by PauToroIsaza** [primeqa/primeqa#434]
Running MRC evaluation gives the following error:
```
Traceback (most recent call last):
  File "/mnt/ptoroisaza/primeqa/primeqa/mrc/run_mrc.py", line 550, in <module>
    main()
  File "/mnt/ptoroisaza/primeqa/primeqa/mrc/run_mrc.py", line 505, in main
    metrics = trainer.evaluate()
  File "/mnt/ptoroisaza/primeqa/primeqa/mrc/trainers/mrc.py", line 203, in evaluate
    output = eval_loop(
  File "/opt/anaconda3/envs/primeqa/lib/python3.8/site-packages/transformers/trainer.py", line 2974, in evaluation_loop
    loss, logits, labels = self.prediction_step(model, inputs, prediction_loss_only, ignore_keys=ignore_keys)
  File "/opt/anaconda3/envs/primeqa/lib/python3.8/site-packages/transformers/trainer.py", line 3217, in prediction_step
    loss, outputs = self.compute_loss(model, inputs, return_outputs=True)
  File "/opt/anaconda3/envs/primeqa/lib/python3.8/site-packages/transformers/trainer.py", line 2553, in compute_loss
    raise ValueError(
ValueError: The model did not return a loss from the inputs, only the following keys: start_logits,end_logits,target_type_logits. For reference, the inputs it received are input_ids,attention_mask.
```
Issue due to Huggingface 4.24.0 update.

Fix works from [https://github.com/primeqa/primeqa/blob/3837f1a663b5ee8cb1519b579fe82a88c8041603/primeqa/mrc/trainers/mrc.py#L38](https://github.com/primeqa/primeqa/blob/3837f1a663b5ee8cb1519b579fe82a88c8041603/primeqa/mrc/trainers/mrc.py#L38)
```
        # FIXME: Work around for a bug in Transformers (4.24.0)
        # Reference: https://github.com/huggingface/transformers/issues/20105
        # -------- START OF FIX --------
        if transformers.__version__ == "4.24.0":
            if "args" not in kwargs:
                kwargs["args"] = TrainingArguments(output_dir="tmp_trainer")

            kwargs["args"].label_names = ["start_positions", "end_positions"]
        # --------  END OF FIX   --------
```

Might have to add to imports in `primeqa/mrc/trainers/mrc.py`:
```
import transformers
```

**Comment by jdpsen** [comment]
@seirasto : Could you please check on this ? Is this same as what you had fixed during 4.2.4.0 testing of CI errors.

**Comment by seirasto** [comment]
I don't think so import transformers is already in mrc.py. It looks like this may be an attempt to run predict instead of eval which is not supported in run_mrc.py. @bhavani105

**Comment by bhavani105** [comment]
@PauToroIsaza Evaluation requires examples with gold answers. Would it be possible to provide some examples of the input data.

**Comment by PauToroIsaza** [comment]
@bhavani105 and @seirasto Sorry if I didn't explain clearly. The fix from https://github.com/primeqa/primeqa/blob/3837f1a663b5ee8cb1519b579fe82a88c8041603/primeqa/mrc/trainers/mrc.py#L38 worked. @avisil asked me to create an issue anyways explaining the problem and that the fix worked. I just had to add that import line but maybe I had a older version of `mrc.py` that didn't have `import transformers`.

The issue isn't with the evaluation input data. It works fine.

**Comment by bhavani105** [comment]
@PauToroIsaza The current version in main https://github.com/primeqa/primeqa/blob/main/primeqa/mrc/trainers/mrc.py 
has the `import transformers.`  Is it possilble to test with this ?
