### ISSUE TITLE
specify which API KEY to chase down on https://github.com/primeqa/primeqa/blob/main/notebooks/mrc/LLM_reader_predict_mode.ipynb

### ISSUE THREAD

**Issue by pleabargain** [primeqa/primeqa#459]
docs say get API key
but docs don't say WHICH API key to get

further
https://bam.res.ibm.com/ is a 404 as of 2023-mar-04

**Comment by avisil** [comment]
Thanks for the comment - we'll specify explicitly which keys to put in. BAM is an IBM internal only option - we'll make this clear in the notebook. 
@seirasto @mihaela-bornea can you please take this up?

**Comment by seirasto** [comment]
This has been resolved by PR #461
