### ISSUE TITLE
Compatibility issues with M1 macs

### ISSUE THREAD

**Issue by nr-bailey** [primeqa/primeqa#465]
When running [dense IR with ColBERT](https://github.com/primeqa/primeqa/blob/main/notebooks/ir/dense/dense_ir.ipynb) and [dense IR with DPR](https://github.com/primeqa/primeqa/blob/main/notebooks/ir/dense/dense_ir_dpr.ipynb) on an M1 Mac, the notebook returns the following error:
> The Kernel crashed while executing code in the the current cell or a previous cell. Please review the code in the cell(s) to identify a possible cause of the failure. Click [here](https://aka.ms/vscodeJupyterKernelCrash) for more info. View Jupyter [log](command:jupyter.viewOutput) for further details.

For both ColBERT and DPR, the kernel crashes when running the indexer (i.e. training the model runs without issue, the problem occurs after).

In the case of ColBERT, the issue occurs when running this chunk:
```
with Run().context(RunConfig(root=args_dict['root'], experiment=args_dict['experiment'], nranks=args_dict['nranks'], amp=args_dict['amp'])):
    colBERTConfig = ColBERTConfig(**args_dict)
    create_directory(colBERTConfig.index_path_)
    encode(colBERTConfig, collection_fn, None, None)
```
And the output immediately before the kernel crashes is as follows:
> $\vdots$
[Mar 09, 16:53:45] >> num_partitions limited to: self.num_partitions = 2
[Mar 09, 16:53:45] [0] 		 Creaing 2 partitions.
[Mar 09, 16:53:45] [0] 		 *Estimated* 922 embeddings.
[Mar 09, 16:53:45] [0] 		 #> Saving the indexing plan to [/var/folders/cv/127kmpt12wj0vkvmtgqtg5x00000gn/T/tmp8l_cp31q/output_dir/test_indexing/indexes/index_name/plan.json](https://file+.vscode-resource.vscode-cdn.net/var/folders/cv/127kmpt12wj0vkvmtgqtg5x00000gn/T/tmp8l_cp31q/output_dir/test_indexing/indexes/index_name/plan.json)

From this, I believe that the issue is being triggered by the `encode()` call. `encode()` calls the following in sequence:
 * `CollectionIndexer.setup()`, which runs without issue because it prints a number of statements to screen.
 * `CollectionIndexer.train()`,
 * `CollectionIndexer.index()`, 
 * `CollectionIndexer.finalize()`

I suspect the issue may be with `CollectionIndexer.index()`, because this is where faiss gets involved, and I am aware of compatibility issues for some versions of faiss and M1 Macs. 

I have tried installing faiss from conda-forge, but the error persists. I have also tried creating a new conda env replicating x86_64 architecture (following [here](https://github.com/conda/conda/issues/12206)) and then using pip install. This produces a different error, triggered when importing faiss, linked to `_swigfaiss`.

Any suggestions on potential solutions?

**Comment by avisil** [comment]
@jdpsen can you please take a look?

**Comment by jdpsen** [comment]
@riyazbhat is looking into this. 
@riyazbhat : please update and take this issue to closure.

**Comment by avisil** [comment]
@riyazbhat is this resolved?

**Comment by riyazbhat** [comment]
Yes, the issue has been resolved. I am closing it now.
