### ISSUE TITLE
Retrieval Augmented Generation using open-source models

### ISSUE THREAD

**Issue by vahuja4** [primeqa/primeqa#484]
Can you please publish an example showing how to use an open-source LLM, like Flan-T5 to do the generation step in the RAG pipeline? How to fine-tune such a model using PrimeQA, etc?

**Comment by avisil** [comment]
Hi - you can check out notebooks such as this: 
https://github.com/primeqa/primeqa/blob/main/notebooks/retriever-reader-pipelines/prompt_reader_with_GPT.ipynb

This example shows inference only. However there are other examples that show how to use RAG techniques and fine-tuning them.  You can also check out Fusion In Decoder code that’s available within our repo. Please let me know if that answers your question.
