### ISSUE TITLE
Fine-tuning an arc model for SQuAD V2

### ISSUE THREAD

**Issue by mfeblowitz** [primeqa/primeqa#486]
I am in urgent need of guidance in fine-tuning one of the mrc models on SQuAD V2.0. Suppression of non-answers is important for our work. We're coming up quite soon on a paper deadline and I need to be able to use one of these models to generate needed data.

I have tried using the `PrimeQA/tydiqa-primary-task-xlm-roberta-large` without fine tuning. It works quite well on questions relevant to the passage, but provides bogus answers on totally irrelevant questions. 

I have tried fine tuning as described in the [mrc](https://github.com/primeqa/primeqa/tree/main/primeqa/mrc) readme and encountered these errors:

1. When trying run parameter `--dataset_name squad_v2` the dataset was found but no `primary_task` element was found for that dataset.
2. When trying instead to specify `--train_file` and a downloaded squad_v2 training dataset, processing the dataset throws an exception when processing the tokenized items from the squad2 train file, finding entries, finding empty `passage_index` values: 

 
<img width="718" alt="Screenshot 2023-05-01 at 5 13 40 PM" src="https://user-images.githubusercontent.com/6854939/235533899-b39e2421-8f0b-45d7-91bf-ab9c782df869.png">

These values are viewed at line 165 of `base.py`:
```
 target = examples['target']
```
It seems like there are several such sets, having something to do with the training data. Tokenization seems to be working, so there's something in how the examples are being populated.

Any quick guidance would be appreciated.

**Comment by mfeblowitz** [comment]
I have identified the issue with item #1 above:  

On line 457 of `run_mrc.py` there is a reference to `data_args.dataset_config_name,`, which is defaulted to `primary_task`.  When line 457 is commented out, the load proceeds as though the train set has been explicitly stated (that is, referring to `squad_v2` as `dataset_name` loads the same squad_vs dataset as from huggingface or from the Stanford SQuAD V2 site.

And it should be n surprise that the processing of tokenized entries errors out in the same manner as stated above.

**Comment by jdpsen** [comment]
@vishwajeetkumar93 : to work on this and update here

**Comment by avisil** [comment]
We had a discussion and the suggestion was to move with FLAN T5 with SQ2 prompting
