### ISSUE TITLE
Profile MRC Code

### ISSUE THREAD

**Issue by jdpsen** [primeqa/primeqa#93]
_aferritto created the following on Apr 01:_  

 Profile MRC Code to look for speedup opportunities.

Some potential ideas before looking:

Extractive Postprocessor:
- replace argsort with argpartition
- replace sorted(){slice] with heapq.topk 

_Original issue: https://github.ibm.com/ai-foundation/PrimeQA/issues/84_

**Comment by jdpsen** [comment]
@bhavani105 : please update the status and the pipeline label for this issue

**Comment by bhavani105** [comment]
This will be done as part of creating primeqa services
